apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fku5505mj-nodejs 
  janus-idp.io/tekton: fku5505mj-nodejs
  backstage.io/kubernetes-id: fku5505mj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fku5505mj-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  