apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fku5505mj-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fku5505mj-nodejs 
  name: fku5505mj-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: fku5505mj-nodejs 
