apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fku5505mj-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe:13badb1a7a14a9eb0a89363d6e443a8b401063db@sha256:da92f78b890e1ca8f0b5638a65fb5963c24b91a58a5a5ec2864eb71133ef5e85
          name: container-image
